### ISSUE TITLE
JSon serialization exception: Unable to make public com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl() accessible: module java.xml does not "exports com.sun.org.apache.xerces.internal.jaxp.datatype" to unnamed module

### ISSUE THREAD

**Issue by leorojasbvc** [prowide/prowide-iso20022#45]
Hello.

We are encountering the following difficulty processing ISO 20022 messages with dates on them.

Considering this sese.024.001.10 message:

```
<?xml version="1.0" encoding="UTF-8"?>
<DataPDU xmlns="urn:swift:saa:xsd:saa.2.0">
	<Body>                 
		<AppHdr xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.01">                         
			<Fr>                                 
				<FIId>                                         
					<FinInstnId>                                                 
						<BICFI>DCVBCOBOXXX</BICFI> <!--BIC de la entidad que envía el mensaje-->
						<Othr>                                                         
							<Id>DCVBCOBOXXX</Id> <!--BIC del DCV-->
						</Othr>                                         
					</FinInstnId>                                 
				</FIId>                         
			</Fr>                         
			<To>                                 
				<FIId>                                         
					<FinInstnId>                                                 
						<BICFI>IMF1COBOXXX</BICFI> <!--BIC de la entidad que recibe el mensaje-->
						<Othr>                                                         
							<Id>DCVBCOBOXXX</Id> <!--BIC del DCV-->
						</Othr>                                         
					</FinInstnId>                                 
				</FIId>                         
			</To>                         
			<BizMsgIdr>20200818X0000121</BizMsgIdr> <!--ID del mensaje-->
			<MsgDefIdr>sese.024.001.10</MsgDefIdr> <!--Tipo de mensaje enviado-->
			<CreDt><!--2020-08-18T09:08:30Z--></CreDt> <!--Fecha y hora de creación del mensaje-->
		</AppHdr>                 
		<Document xmlns="urn:iso:std:iso:20022:tech:xsd:sese.024.001.10">                         
			<SctiesSttlmTxStsAdvc>                                 
				<TxId>
					<AcctOwnrTxId>115</AcctOwnrTxId><!--Referencia de transacción informada en el tag TxId del mensaje sese.023-->
					<AcctSvcrTxId>20200818T00052360</AcctSvcrTxId><!--Referencia única de la transacción en el DCV-->
				</TxId>
				<MtchgSts>
					<Mtchd>MACH</Mtchd><!--Indicador de que la transacción se encuentra emparejada-->
				</MtchgSts>
				<TxDtls>
					<TradDt>
						<Dt>
							<DtTm>2020-08-18T08:01:30</DtTm><!--Fecha y hora de negociación informada en el mensaje sese.023-->
						</Dt>
					</TradDt>
				</TxDtls>
			</SctiesSttlmTxStsAdvc>                 
		</Document>         
	</Body>
</DataPDU>
```

We try to make a JSon object out of it using Prowide this way:

MxSese02400110 prowideFuncional=MxSese02400110.parse(message);
System.out.println(prowideFuncional.toJson());

But every time the toJson() method is called, we get a the exception Unable to make public com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl() accessible: module java.xml does not "exports com.sun.org.apache.xerces.internal.jaxp.datatype" to unnamed module

And this only happens when the XML has any dates on it.

If i remove them, the Exception goes away.

Can you help me with this?

**Comment by leorojasbvc** [comment]
Update: I am getting this very same exception even running the included example. MxToJsonExample without any modification.

There is something in the execution environment there is no doubt about it, but what is it? if i remove the Date tags it works perfectly.

A little help please.

**Comment by leorojasbvc** [comment]
Update 2: I tried using Java 1.8 Version and it works!

So there is something  weird on the lib using versions above 8.

**Comment by zubri** [comment]
Since Java 9 and the introduction of modules some JDK packages are not available by default. In particular this library requires the jaxb jars. 

In Java 9+ you can enable the modules explicitly or you can include an implementation as jar dependency. For example

	implementation 'javax.xml.bind:jaxb-api:2.3.1'
	implementation 'com.sun.xml.bind:jaxb-impl:2.3.3'

**Comment by Gems** [comment]
Adding the mentioned dependencies (`javax.xml.bind:jaxb-api:2.3.1`, `com.sun.xml.bind:jaxb-impl:2.3.3`) or their most up-to-date versions doesn't help to solve the issue.

Adding dependency `org.glassfish.jaxb:jaxb-runtime:3.0.2` doesn't help either.

With the most up-to-date `gson:2.9.0` it gives:
```
com.google.gson.JsonIOException: Failed making field 'com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl#eon' accessible; either change its visibility or write a custom TypeAdapter for its declaring type
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:22) ~[gson-2.9.0.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:158) ~[gson-2.9.0.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:101) ~[gson-2.9.0.jar:na]
	at com.google.gson.Gson.getAdapter(Gson.java:501) ~[gson-2.9.0.jar:na]
        … omitted here
	at com.prowidesoftware.swift.model.mx.AbstractMX.toJson(AbstractMX.java:646) ~[pw-iso20022-SRU2021-9.2.6.jar:SRU2021-9.2.6]
        … omitted here
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.math.BigInteger com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl.eon accessible: module java.xml does not "opens com.sun.org.apache.xerces.internal.jaxp.datatype" to unnamed module @4d937939
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[na:na]
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172) ~[na:na]
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:19) ~[gson-2.9.0.jar:na]
	... 42 common frames omitted
```

Didn't find a solution yet 🤷🏻‍♂️

**Comment by Gems** [comment]
I've found out that if in [the place of registering an Adapter for `XMLGregorianCalendar` class](https://github.com/prowide/prowide-iso20022/blob/a4a596c2ca8051dae6c277ffa8d115a000fd4ba3/iso20022-core/src/main/java/com/prowidesoftware/swift/model/mx/AbstractMX.java#L641) instead of `registerTypeAdapter` use `registerTypeHierarchyAdapter` then the problem dissapears.

**Comment by zubri** [comment]
Thanks for the fix @Gems
