### ISSUE TITLE
Erro: java.lang.ClassNotFoundException: com.prowidesoftware.swift.model.field.Field

### ISSUE THREAD

**Issue by anderson-indiano** [prowide/prowide-iso20022#52]
Hello,

I'm having problems running an application in an approval environment,
I'm using a pw-swift-core/SRU2021-9.2.13 library, and the error below is occurring:
please help.

Caused by: java.lang.NoClassDefFoundError: com.prowidesoftware.swift.model.field.Field
at java.lang.J9VMInternals.prepareClassImpl(Native Method)
at java.lang.J9VMInternals.prepare(J9VMInternals.java:302)
at java.lang.Class.getDeclaredMethods(Class.java:975)
at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613)
at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524)
at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnot
ationBeanPostProcessor.java:247)
... 12 more
Caused by: java.lang.ClassNotFoundException: com.prowidesoftware.swift.model.field.Field
at java.net.URLClassLoader.findClass(URLClassLoader.java:610)
at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:925)
at java.lang.ClassLoader.loadClass(ClassLoader.java:870)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:343)
at java.lang.ClassLoader.loadClass(ClassLoader.java:853)
... 19 more

exit 1

**Comment by ptorres-prowide** [comment]
Hello Anderson, could you share your complete pom.xml file?
Thanks
Regards
Pablo
